apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: objectstore
spec:
  type: bindings.aws.s3
  version: v1
  metadata:
    - name: bucket
      value: atlan-bucket
    - name: region
      value: us-east-1
    - name: endpoint
      value: ${ATLAN_BASE_URL}/api/blobstorage
    - name: accessKey
      value: ${SDR_CLIENT_ID}
    - name: secretKey
      value: ${SDR_CLIENT_SECRET}
    - name: forcePathStyle
      value: "true"
