"""
respx-based HTTP replay fixture for OpenAPI Spec Loader connector.

Generated by /scrape-source Task 8.

Usage in tests:
    def test_something(mock_openapi_spec):
        # All httpx calls to the spec URL are intercepted and return scraped data.
        # No real network calls are made.
        response = httpx.get(spec_url)  # intercepted by respx
        spec = response.json()
        assert spec["info"]["title"] == "Swagger Petstore - OpenAPI 3.0"

    async def test_async(mock_openapi_spec):
        async with httpx.AsyncClient() as client:
            response = await client.get(spec_url)  # intercepted by respx
        spec = response.json()
        assert "paths" in spec

Note: this connector's "API" is a single HTTP GET of a static OpenAPI spec document.
There is no authentication, no pagination, and only one endpoint to mock. Both APISpec
and APIPath data are embedded in the single response body (under `info` and `paths`).
"""

import json
from collections.abc import Iterator
from pathlib import Path

import httpx
import pytest
import respx

# ---------------------------------------------------------------------------
# Core fixture: extracts directory
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def extracts_dir() -> Path:
    """Return the absolute path to the extracts/openapi/ directory.

    The conftest.py lives at extracts/openapi/replay/conftest.py,
    so extracts_dir is two levels up from this file.
    """
    return Path(__file__).parent.parent.resolve()


# ---------------------------------------------------------------------------
# Metadata helpers
# ---------------------------------------------------------------------------


@pytest.fixture(scope="session")
def scrape_metadata(extracts_dir: Path) -> dict:
    """Load metadata.json for the extract."""
    metadata_path = extracts_dir / "metadata.json"
    if not metadata_path.exists():
        pytest.skip(f"metadata.json not found at {metadata_path} — run scrape.py first")
    with open(metadata_path) as f:
        return json.load(f)


def _load_spec_url(extracts_dir: Path) -> str:
    """Read the spec URL from metadata.json (recorded as base_url by scrape.py)."""
    metadata_path = extracts_dir / "metadata.json"
    if metadata_path.exists():
        with open(metadata_path) as f:
            return json.load(f).get(
                "base_url", "https://petstore3.swagger.io/api/v3/openapi.json"
            )
    return "https://petstore3.swagger.io/api/v3/openapi.json"


def _load_spec_response(extracts_dir: Path) -> tuple[dict, dict]:
    """Load raw/spec/response_001.json and raw/spec/headers_001.json."""
    body_path = extracts_dir / "raw" / "spec" / "response_001.json"
    headers_path = extracts_dir / "raw" / "spec" / "headers_001.json"

    if not body_path.exists():
        raise FileNotFoundError(
            f"Spec response not found at {body_path} — run scrape.py first"
        )

    with open(body_path) as f:
        body = json.load(f)

    header_info: dict = {"status_code": 200, "headers": {}}
    if headers_path.exists():
        with open(headers_path) as f:
            header_info = json.load(f)

    return body, header_info


# ---------------------------------------------------------------------------
# Fixture: mock_openapi_spec
# ---------------------------------------------------------------------------


@pytest.fixture
def mock_openapi_spec(extracts_dir: Path) -> Iterator[respx.MockRouter]:
    """Intercept all httpx calls to the OpenAPI spec URL and return scraped data.

    Yields a respx.MockRouter. Tests using this fixture cannot make real network
    calls to the spec URL — any unmocked URL raises an error.

    The mocked URL is read from metadata.json (base_url), so it automatically
    matches the URL the connector will use at runtime.

    Both APISpec metadata (info block) and all APIPath records (paths block) are
    present in the single mocked response — there is only one endpoint to mock.
    """
    spec_url = _load_spec_url(extracts_dir)
    body, header_info = _load_spec_response(extracts_dir)

    response_headers = {
        k: v for k, v in header_info.get("headers", {}).items() if isinstance(v, str)
    }
    status_code = header_info.get("status_code", 200)

    with respx.mock(assert_all_mocked=True) as router:
        # Single route: GET <spec_url> → return saved spec document
        router.get(spec_url).mock(
            return_value=httpx.Response(
                status_code,
                json=body,
                headers=response_headers,
            )
        )
        yield router
