name: Unit Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
    timeout-minutes: 10
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Get branch name
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: get_branch

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.7.3"

      - name: Install dependencies
        run: uv sync --frozen --all-groups

      - name: Run Tests with Coverage
        run: |
          uv run coverage run -m pytest tests/unit
          uv run coverage xml
          uv run coverage html
          uv run coverage report --fail-under=30

      - name: Comment Coverage Report on PR
        if: ${{ always() && github.event_name == 'pull_request' }}
        uses: orgoro/coverage@3f13a558c5af7376496aa4848bf0224aead366ac # v3.2
        with:
          coverageFile: coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
